sudo: required
language: python
services:
- docker
before_install:
- sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname
  -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" registry.datadrivendiscovery.org
  --password-stdin
- sudo docker-compose -f docker-compose-travis.yml up -d
script:
- sudo docker-exec ta2 python ta2_server.py &
- sudo docker-exec ta2 pytest -n 4
env:
  matrix:
  - secure: hXKf1wG1uQXLnKL2cuEreyqmqRsBY5+wn4pF9CYHnPUmcG0bxjRhL9WQrNgxE5bUDTU/q/frMisHAqcvAuMGOaVx5pfl+u8y5sE7kUY4ruNAFiM8xdcTwuO3ScoTu9FmRwD3v4svlUN/m3qFB1Jn14s0Y+3jSgSPY8m4P/W+xJ1Nf7O32KKW5bed2UdMmkAyYCpv5fdRY5C0uowLGCUwK0rpfGFYcOGuuIIvr4MUBMnVGDFY9Yd6iIenol5sfTf23pu6xLkd8SH6z4zlD3Pc5ncUnlusugiSPk6SIMGsFRP2Fm0O/2IrCXcPE+TdVCwcOlzx7GLMlFG7uVb6grxOgqN3wV9RhyaOpg+E2JRYjE8ssZ/vQOHxpkfRQbX9vBpl+TVoQZJOSj/oQUQ2Qo2/mCF316NcNmRmqqE0ROOziq+vlNaChYdNANniUukzgGSSWrc7cUwFiD+hBffin2B0VarJu8pmi2oFhw2GLp+y9JEpqv+3AIwCmBBjgZLaDEaz5x6mX40ndiQBd5ZkX8nAE2f0tQ1hImZqv2a1yUlU2u3B0FKiwOYG/xOj4zEyCNuRcGG8OTnZpB4msAC5hSGABTiZVc5xZJHCwqU6CDrywVK035m6wJFb5QDAjY7h5SnRzwNGeUPH3tAdV7XhGXu7L2M2+c6CnSeLGXrTpSDuqDA=
  - secure: t8YzueZbE14RH4KBklv6aWWgNb2EjC2v6w/WIxNasS0OzMDBjVlHBWdpMc4nUlBeH6m3h3Dg1cFG+GtOh1Ea2TZVHO5HJMgZcwKcBm5PweSSJJtzEaSNYcsYio8oHsJysFtyCHYs12jUr1xqRMMH2i8tLiz4L3NUOVt+csblAYs8nOYYxv54SnVOnlVhSItWdYZWn4X5z+kdfdfwB5ym+m1k+lSoLieknPVqBa0vx9usuwExRoab0aBdY2+MK4uwIILJIdVeyD7ltqF+xjVkQ/X+Bqvs35H5/OD3+LeZNW6K4i3yKj7YoGnwCF8zmO9UkmonOPckusDsqDo+80fv4Whs1R+dfPglkpSPSGD+lTp6LVPo1puQu4c6ZMxfBGiH9hLkcA/QSYs/QjTKSdS/db/rJaTs2zeQ8g1efmkYEEkVp8LQsWxxq3P9p0K3qW6G/Nw0pj+0C/WzqJNwJpSCcpIDszgQoWJynWGpfwub6jLE10HJrOujH8vSQ4n7Ek8Nz4fWrCJIuCI5YlWecYuP6BCr0jh8TQ+M+Zyu3SmGNyfmgOAEuVMMFDqw797l89dQXSAnz3H1kWsIlFDq/npwE/LUy4LkExkQ8yy+K39cSCnGCnU4pRy3P61LFu+++QrJYGvl/6gJsovOLOXA0dRfpM9WJlhHSva9/zSW2HAze54=
