sudo: required
language: python

services:
  - docker

before_install: 
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose up -f docker-compose-travis.yml up -d

script:
  - sudo docker-exec ta2 python ta2_server.py &
  - sudo docker-exec ta2 pytest -n 4


