sudo: required
language: python
services:
- docker
before_install:
- sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname
  -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" registry.datadrivendiscovery.org
  --password-stdin
- sudo docker-compose -f docker-compose-travis.yml up -d
script:
- sudo docker-exec ta2 python ta2_server.py &
- sudo docker-exec ta2 pytest -n 4
env:
  global:
  - secure: M4ChKcynkwmvKxpFz7+/bZAWJzIvTvOk8LX2xea47+tXwHLsp/BXKISp0ypCQt0qiwH6vPMgpWc8hPQRFl0pAphaO2kvgkUbnvp5Hcmqi+YyIFCYKfhi884GYvYI2TXcLHyK/QesJYhVQWfUmcYCZhZMVkumD0HicvbRDdG+b788K3RAgTIQKhJzerCyvE/XQFKFX7AYrrOcIaTUAgAa1r+a7IH3Xim1wXNh9IB27JZvHyKj5VRgLsfzkHzUKHfVymoK079vZh0cuS+PZ15eNYxti1zLjLCr11OB53oBCrYOdfF1S6+C4neouoX7MbtEitD6ipd2XSn3pvPlWbknFNXRWcyNVIizPOhvXYb4EkmgiGVaX6uHt2J9NlzWIH2TtH8+QOWUq0e/KpTcFNznHvpudY1uZnJbvIRVlonkiN74gK188oURuJVAEHMFztoY13aNLHQAw1IS6ubz0X4dFJ33lM7xIENSWRzhPVJr9uyTv16Ly4ByEAfDzWJqPKfn87YjDJaazA3+SDK9PIkD4x4zE7X5Uto7GiHdlT+4KJvJytVNP4k1Lb8dGOduBsW+0QuErbTS+cvuav+Ypg8zlNSIFmYfOSr60pfDKc2rx6Owg0XSOF4uP89jMpLsJLLkQjt2c9H1xiGS6jAZ/XdLzpO9TnokkbhiPDgTPw9G+x0=
  - secure: GQuLylG+Jpx2dOa6hhas4lExqJc/Xv3ZSvlURF+vwF4FZYeo9ayR3V48Izo1RGTtJaxHjzlZdH9NPssljIV++ilPiYWvlh5PvCubuvTyCyPcTgc2Oml/NnGmBty7fsG0FBvrkXbg0QTgBsqTwfroOKXB7qZUBy148L+yGE9tI4vy6v/y9U4tQJ+nDpZoL31NGm2C7VzBKDtboZsuhiEpMMjjLKX57en9GZgSrHDQxfEvecfSTdKael4nD+P95l9JcbE/qKLicAorKt/DfcD/CRMoyYsPE5VbR5209QNkQWcxx/DkYnTn9ys5AsM4k1b0vjeuR3e4QX2Zw64qxk3u4qwrxagipmm5GrgZDOS5gZq4FDf9fb3V5SwvHAzLnPbyVDNMqT5mrwkgILT6Aek1Zh+ZX+PUu/W6+tVvmp7Fdf/Q8rd0aOd8aDwOO3jDukKsKiGOpToLPSFTfC/BJ0FwhbAvgcpO3heq5CP7OI1Dupo9JI7HP9TWZwbB23fQ3cTDfDPdWzrVIiM0p+5Enre8jDHMyhfbfKbtEVDW78scCsCsIS3G+eBTSoHDqpb9V400q8geLoMWZgWvGMHUQWS2okyA6HFRiSwmPC6JoD9t1H6tIW9AcWG9IVo5BulZYP9PUaxuw41yUR3+FnytRo0YC4bmSBrgGGEwtdb7IXKnoEo=
