sudo: required
language: python
services:
- docker
before_install:
- sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname
  -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- echo $DOCKER_USERNAME
- echo "$DOCKER_USERNAME"
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME registry.datadrivendiscovery.org
  --password-stdin
- sudo docker-compose -f docker-compose-travis.yml up -d
script:
- sudo docker-exec ta2 python ta2_server.py &
- sudo docker-exec ta2 pytest -n 4
