version: '2.4'
services:
  d3m:
    build:
      context: .
    shm_size: '2gb'
    container_name: ta2
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
#    runtime: nvidia
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${VOLUMES}:/volumes
      - ${DATASETS}:/datasets
      - ${TA2}:/d3m-ta2
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    network_mode: "bridge"
    links:
      - mongodb
#    mem_limit: 40G
  mongodb:
    image: mongo:latest
    container_name: "ta2-mongodb"
    environment:
    - MONGO_DATA_DIR=/data/db
#    volumes:
#    - ./data/db:/data/db
    network_mode: "bridge"
    ports:
    - 27017:27017
      

