version: '2.4'
services:
  d3m:
    build:
      context: .
    shm_size: '2gb'
    container_name: ta2
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
#    runtime: nvidia
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${VOLUMES}:/volumes
      - ${DATASETS}:/datasets
      - ${TA2}:/d3m-ta2
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    network_mode: "bridge"
      

