version: '2.4'
services:
  d3m:
    build:
      context: .
    shm_size: '2gb'
    container_name: ta2
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
#    runtime: nvidia
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${VOLUMES}:/volumes
      - ${DATASETS}:/datasets
      - ${TA2}:/d3m-ta2
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    network_mode: "bridge"
    links:
      - redis
#    mem_limit: 40G
  redis:
    image: 'redislabs/rejson:latest'
    container_name: ta2-redis
    environment:
    # ALLOW_EMPTY_PASSWORD is recommended only for development.
    - ALLOW_EMPTY_PASSWORD=yes
#    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
    - '6379:6379'
    network_mode: "bridge"
#    volumes:
#    - 'redis_data:/bitnami/redis'
      

